# Generated by Django 5.1.15 on 2026-08-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Sarlavha')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Rasm')),
                ('link_type', models.CharField(blank=True, choices=[('brand', 'Brend'), ('product', 'Mahsulot'), ('url', 'URL')], max_length=20, verbose_name='Havola turi')),
                ('link_value', models.CharField(blank=True, max_length=255, verbose_name='Havola qiymati')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Boshlanish')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugash')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Bannerlar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PromoScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Sarlavha')),
                ('body', models.TextField(blank=True, verbose_name='Matn')),
                ('image', models.ImageField(blank=True, null=True, upload_to='promos/', verbose_name='Rasm')),
                ('placement', models.CharField(choices=[('before_login', 'Kirishdan oldin'), ('after_login', 'Kirgandan keyin')], default='after_login', max_length=20, verbose_name='Joylashuv')),
                ('skip_after_seconds', models.PositiveIntegerField(default=3, verbose_name='Skip (soniya)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Reklama ekrani',
                'verbose_name_plural': 'Reklama ekranlari',
            },
        ),
    ]
