# Generated by Django 6.1.1 on 2026-10-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='bg_color',
            field=models.CharField(blank=True, default='#009D4D', help_text="Rasm bo'lmaganda fon rangi. Masalan: #009D4D", max_length=7, verbose_name='Fon rangi (matn banner)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='subtitle',
            field=models.CharField(blank=True, help_text="Rasm bo'lmaganda ko'rinadigan qo'shimcha matn.", max_length=300, verbose_name='Tavsif (matn banner uchun)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, help_text="Ixtiyoriy. Bo'sh qoldirilsa, matn banner ko'rsatiladi.", null=True, upload_to='banners/', verbose_name='Rasm'),
        ),
    ]