# Generated by Django 5.1.15 on 2026-08-28 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Yopilgan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('courier', models.ForeignKey(limit_choices_to={'role': 'courier'}, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL, verbose_name='Dastavkachi')),
            ],
            options={
                'verbose_name': 'Marshrut',
                'verbose_name_plural': 'Marshrutlar',
                'ordering': ['-date'],
                'unique_together': {('courier', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DeliveryStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_delivered', models.BooleanField(default=False, verbose_name='Yetkazildi')),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('collected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name="Yig'ilgan pul")),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_stop', to='orders.order', verbose_name='Buyurtma')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='delivery.deliveryroute')),
            ],
            options={
                'verbose_name': 'Yetkazish nuqtasi',
                'verbose_name_plural': 'Yetkazish nuqtalari',
                'ordering': ['sequence'],
            },
        ),
    ]
