# Generated by Django 5.1.15 on 2026-08-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=10, unique=True, verbose_name='Platforma')),
                ('latest_version', models.CharField(max_length=20, verbose_name='Oxirgi versiya')),
                ('min_version', models.CharField(help_text='Bundan past versiyalar majburiy yangilanadi.', max_length=20, verbose_name='Minimal kerakli versiya')),
                ('store_url', models.URLField(blank=True, verbose_name="Do'kon havolasi (Play/App Store)")),
                ('release_notes', models.TextField(blank=True, verbose_name='Yangiliklar')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ilova versiyasi',
                'verbose_name_plural': 'Ilova versiyalari',
            },
        ),
    ]
