# Generated by Django 5.1.15 on 2026-08-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversion',
            name='apk_file',
            field=models.FileField(blank=True, help_text="Android APK faylini shu yerga yuklang. Foydalanuvchi 'Yangilash' bosganda shundan yuklab oladi.", null=True, upload_to='apk/', verbose_name='APK fayl (Android)'),
        ),
    ]