# Generated by Django 5.1.15 on 2026-09-05 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_appversion_apk_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_phone', models.CharField(blank=True, help_text="Tasdiqlash uchun do'kon egasi shu raqamga bog'lanadi.", max_length=20, verbose_name='Admin telefon raqami')),
                ('admin_name', models.CharField(blank=True, max_length=100, verbose_name='Admin ismi')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sozlama',
                'verbose_name_plural': 'Sozlamalar',
            },
        ),
    ]