# Generated by Django 6.1.1 on 2026-09-26 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_shop_is_approved'),
        ('core', '0003_siteconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(blank=True, max_length=200, verbose_name="Do'kon nomi")),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('message', models.TextField(verbose_name='Fikr / taklif')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='accounts.shop', verbose_name="Do'kon")),
            ],
            options={
                'verbose_name': 'Fikr va taklif',
                'verbose_name_plural': 'Fikr va takliflar',
                'ordering': ['-created_at'],
            },
        ),
    ]