# Generated by Django 5.1.15 on 2026-08-28 04:39

import accounts.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Viloyat nomi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Viloyat',
                'verbose_name_plural': 'Viloyatlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tuman nomi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='accounts.region', verbose_name='Viloyat')),
            ],
            options={
                'verbose_name': 'Tuman',
                'verbose_name_plural': 'Tumanlar',
                'ordering': ['region__name', 'name'],
                'unique_together': {('region', 'name')},
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('shop', "Do'kon egasi"), ('courier', 'Dastavkachi'), ('sales', 'Sotuvchi'), ('accountant', 'Buxgalter'), ('admin', 'Administrator')], default='shop', max_length=20, verbose_name='Rol')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Telefon raqam')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='Ism familiya')),
                ('push_token', models.CharField(blank=True, max_length=255, verbose_name='Push token')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='accounts.region', verbose_name='Biriktirilgan viloyat')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Do'kon nomi")),
                ('image', models.ImageField(blank=True, null=True, upload_to=accounts.models.shop_logo_path, verbose_name="Do'kon rasmi")),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Kenglik')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Uzunlik')),
                ('address_text', models.CharField(blank=True, max_length=255, verbose_name='Manzil (matn)')),
                ('debt_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Qarz balansi')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, help_text="Do'kon ko'pi bilan qancha qarzga ola oladi. 0 = limitsiz.", max_digits=14, verbose_name='Nasiya limiti')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_new', models.BooleanField(default=True, help_text="Admin/dastavkachi hali ko'rmagan yangi do'kon.", verbose_name='Yangi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Ro'yxatdan o'tgan sana")),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shops', to='accounts.district', verbose_name='Tuman')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to=settings.AUTH_USER_MODEL, verbose_name='Egasi')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shops', to='accounts.region', verbose_name='Viloyat')),
            ],
            options={
                'verbose_name': "Do'kon",
                'verbose_name_plural': "Do'konlar",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['region', 'district'], name='accounts_sh_region__67977e_idx'), models.Index(fields=['is_new'], name='accounts_sh_is_new_8ba559_idx')],
            },
        ),
    ]
