# Generated by Django 5.1.15 on 2026-08-28 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Kategoriya nomi')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='Slug')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='categories/icons/', verbose_name='Ikonka')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Brend nomi')),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True, verbose_name='Slug')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/logos/', verbose_name='Brend logotipi')),
                ('is_official', models.BooleanField(default=False, verbose_name='Rasmiy distribyutor')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brands', to='catalog.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Brend',
                'verbose_name_plural': 'Brendlar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Mahsulot nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/full/', verbose_name="To'liq rasm")),
                ('thumbnail', models.ImageField(blank=True, help_text="Ro'yxatda ishlatiladi. Yuklashda avtomatik yaratiladi.", null=True, upload_to='products/thumbs/', verbose_name='Kichik rasm (thumbnail)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Narxi')),
                ('unit', models.CharField(choices=[('dona', 'dona'), ('blok', 'blok'), ('karton', 'karton'), ('kg', 'kg'), ('litr', 'litr'), ('qop', 'qop')], default='dona', max_length=10, verbose_name="O'lchov birligi")),
                ('items_per_pack', models.PositiveIntegerField(default=1, verbose_name='Qadoqdagi dona soni')),
                ('stock', models.IntegerField(default=0, verbose_name='Ombordagi qoldiq')),
                ('min_order_qty', models.PositiveIntegerField(default=1, verbose_name='Minimal zakaz miqdori')),
                ('is_new', models.BooleanField(default=False, verbose_name='Yangi')),
                ('is_promo', models.BooleanField(default=False, verbose_name='Aksiya')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Reyting')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.brand', verbose_name='Brend')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['category', 'is_active'], name='catalog_bra_categor_3903ff_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'is_active'], name='catalog_pro_brand_i_ca0f3c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='catalog_pro_categor_891fe8_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='catalog_pro_name_f603c0_idx'),
        ),
    ]
