# Generated by Django 5.1.15 on 2026-08-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='brand',
            name='catalog_bra_categor_3903ff_idx',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='category',
        ),
        migrations.AddField(
            model_name='brand',
            name='categories',
            field=models.ManyToManyField(help_text='Bu brend qaysi kategoriyalarga tegishli (bir yoki bir nechta).', related_name='brands', to='catalog.category', verbose_name='Kategoriyalar'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text="Ro'yxatda ishlatiladi.", null=True, upload_to='products/thumbs/', verbose_name='Kichik rasm (thumbnail)'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'category', 'is_active'], name='catalog_pro_brand_i_31a41c_idx'),
        ),
    ]